In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [26]:
data_out = pd.read_pickle('results_baseline_2026-04-25_16-21-50.pkl')

In [43]:
data_out.keys()

dict_keys(['model', 'run_id', 'best_val_loss', 'test_loss', 'predictions', 'targets', 'sample_labels', 'bin_labels', 'latent_vector', 'train_losses', 'val_losses', 'val_metrics', 'latent_diagnostics', 'test_metrics'])

In [ ]:
samples = np.unique(data_out['sample_labels'])

In [28]:
data = pd.read_csv("../../../data/data_merged.csv")

In [68]:
input = data[data['sample-eventid'].isin(samples)]
train_input = data[~data['sample-eventid'].isin(samples)]

In [69]:
train_input

,sample-eventid,bin_uri,occurrences,total_reads,seq,tot_repl_w_reads,kingdom,phylum,class,order,...,collection_end_date,SumExcessSpecimens,ExcessNumberTaxa,latitude,longitude,tot_repl,repl_w_reads_fractn,Excess,total_reads_per_sample,avg_reads
0,BIOPER00065,BOLD:AAA0988,0,2,AATAAATAATATAAGATTTTGACTTTTACCCCCATCATTAACTCTC...,1,Animalia,Arthropoda,Insecta,Lepidoptera,...,NaN,0.0,0.0,NaN,NaN,3,0.333333,0,684736,0.666667
1,BIOPER00065,BOLD:AAA1415,0,2,AATAAATAATATAAGATTTTGACTTTTACCCCCATCTCTAACTTTA...,1,Animalia,Arthropoda,Insecta,Lepidoptera,...,NaN,0.0,0.0,NaN,NaN,3,0.333333,0,684736,0.666667
2,BIOPER00065,BOLD:AAA1421,0,120,AATAAATAATATAAGTTTTTGACTTCTCCCCCCTTCTTTAATTCTT...,3,Animalia,Arthropoda,Insecta,Lepidoptera,...,NaN,0.0,0.0,NaN,NaN,3,1.000000,0,684736,40.000000
3,BIOPER00065,BOLD:AAA2438,0,10,AATAAATAACATAAGTTTTTGACTTTTACCACCTTCTTTAACTCTT...,2,Animalia,Arthropoda,Insecta,Lepidoptera,...,NaN,0.0,0.0,NaN,NaN,3,0.666667,0,684736,3.333333
4,BIOPER00065,BOLD:AAA5023,0,7,AATAAACAATATAAGTTTTTGACTCCTTCCCCCCTCTTTAACTCTT...,2,Animalia,Arthropoda,Insecta,Lepidoptera,...,NaN,0.0,0.0,NaN,NaN,3,0.666667,0,684736,2.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316304,GZXAE6,BOLD:AGO4011,1,163,AATAAACAATATAAGATTTTGATTATTACCTCCTTCATTAACACTT...,2,Animalia,Arthropoda,Insecta,Diptera,...,2023-12-06,0.0,0.0,-20.794918,44.1662,3,0.666667,0,203752,54.333333
316305,GZXAE6,BOLD:AGO9189,0,3,AATAAATAACATAAGATTTTGACTATTACCCCCTTCTATCACTTTA...,1,Animalia,Arthropoda,Insecta,NaN,...,2023-12-06,0.0,0.0,-20.794918,44.1662,3,0.333333,0,203752,1.000000
316306,GZXAE6,BOLD:AGR0227,0,91,TATAAACAATATAAGATTTTGATTATTACCACCATCATTAACTCTT...,1,Animalia,Arthropoda,Insecta,NaN,...,2023-12-06,0.0,0.0,-20.794918,44.1662,3,0.333333,0,203752,30.333333
316307,GZXAE6,BOLD:AGV6048,0,4,AATAAATAACATAAGATTTTGACTATTACCCCCTTCTATAACTTTA...,1,Animalia,Arthropoda,Insecta,NaN,...,2023-12-06,0.0,0.0,-20.794918,44.1662,3,0.333333,0,203752,1.333333
316308,GZXAE6,BOLD:AGZ0490,0,6,AACCAATAATTTAAGATTTTGACTATTACCCGTATCTTTAAACTTA...,1,Animalia,Arthropoda,Insecta,NaN,...,2023-12-06,0.0,0.0,-20.794918,44.1662,3,0.333333,0,203752,2.000000

In [49]:
data_out['latent_vector']

array([[ 7.31600076e-02, -6.91405777e-03, -2.33075116e-02, ...,
         6.59554452e-02,  4.38072197e-02, -7.64493942e-02],
       [-4.48906329e-04,  3.00201384e-04,  1.13368325e-04, ...,
        -2.63818714e-04, -5.23181407e-05,  7.36872025e-04],
       [-8.86159539e-02,  3.01176440e-02,  8.26203730e-03, ...,
        -5.97603917e-02, -1.74582321e-02,  1.34766027e-01],
       ...,
       [ 9.68142820e-04, -7.08068546e-04, -3.57534067e-04, ...,
         8.33752798e-04,  4.68839251e-04, -1.17226038e-03],
       [ 1.65894435e-05, -1.85973200e-04, -7.65215591e-05, ...,
         3.89572124e-05,  1.13994596e-04,  1.73246372e-05],
       [ 3.98591001e-05, -7.10999984e-06, -4.82564647e-05, ...,
         4.75138659e-05,  1.40397287e-05, -7.16185459e-05]],
      shape=(108816, 10), dtype=float32)

In [53]:
pred = pd.DataFrame({'prediction': data_out['predictions'], 'targets': data_out['targets'], 'sample_labels': data_out['sample_labels'], 'bin_labels': data_out['bin_labels']})
pred = pd.concat([pred, pd.DataFrame(data_out['latent_vector'], columns=[f'latent_{i}' for i in range(data_out['latent_vector'].shape[1])])], axis=1)

In [63]:
all = pd.merge(input, pred, left_on=['sample-eventid', 'bin_uri'], right_on=['sample_labels', 'bin_labels'], how='outer').drop(columns=['seq', 'kingdom', 'phylum', 'class']).set_index(['sample-eventid', 'bin_uri'])

In [67]:
data

,sample-eventid,bin_uri,occurrences,total_reads,seq,tot_repl_w_reads,kingdom,phylum,class,order,...,collection_end_date,SumExcessSpecimens,ExcessNumberTaxa,latitude,longitude,tot_repl,repl_w_reads_fractn,Excess,total_reads_per_sample,avg_reads
0,BIOPER00065,BOLD:AAA0988,0,2,AATAAATAATATAAGATTTTGACTTTTACCCCCATCATTAACTCTC...,1,Animalia,Arthropoda,Insecta,Lepidoptera,...,NaN,0.0,0.0,NaN,NaN,3,0.333333,0,684736,0.666667
1,BIOPER00065,BOLD:AAA1415,0,2,AATAAATAATATAAGATTTTGACTTTTACCCCCATCTCTAACTTTA...,1,Animalia,Arthropoda,Insecta,Lepidoptera,...,NaN,0.0,0.0,NaN,NaN,3,0.333333,0,684736,0.666667
2,BIOPER00065,BOLD:AAA1421,0,120,AATAAATAATATAAGTTTTTGACTTCTCCCCCCTTCTTTAATTCTT...,3,Animalia,Arthropoda,Insecta,Lepidoptera,...,NaN,0.0,0.0,NaN,NaN,3,1.000000,0,684736,40.000000
3,BIOPER00065,BOLD:AAA2438,0,10,AATAAATAACATAAGTTTTTGACTTTTACCACCTTCTTTAACTCTT...,2,Animalia,Arthropoda,Insecta,Lepidoptera,...,NaN,0.0,0.0,NaN,NaN,3,0.666667,0,684736,3.333333
4,BIOPER00065,BOLD:AAA5023,0,7,AATAAACAATATAAGTTTTTGACTCCTTCCCCCCTCTTTAACTCTT...,2,Animalia,Arthropoda,Insecta,Lepidoptera,...,NaN,0.0,0.0,NaN,NaN,3,0.666667,0,684736,2.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317031,GZYSTR,BOLD:AGT3966,2,4704,AATAAATAATATAAGTTTCTGAATACTCCCCCCTTCAATTACACTT...,3,Animalia,Arthropoda,Insecta,Diptera,...,2022-03-13,150.0,1.0,5.789432,-73.54972,3,1.000000,1,981359,1568.000000
317032,GZYSTR,BOLD:AGV0195,0,5,AATAAATAATTTAAGATTTTGATTATTACCTTCTTCTTTAATTTTA...,1,Animalia,Arthropoda,Insecta,NaN,...,2022-03-13,150.0,1.0,5.789432,-73.54972,3,0.333333,1,981359,1.666667
317033,GZYSTR,BOLD:AGW8153,0,14,AATAAATAATATAAGATTTTGATTACTACCTCCTTCTTTATTATTA...,3,Animalia,Arthropoda,Insecta,Diptera,...,2022-03-13,150.0,1.0,5.789432,-73.54972,3,1.000000,1,981359,4.666667
317034,GZYSTR,BOLD:AGW9919,0,4,AATAAACAATATAAGATTCTGATTACTACCCCCTTCTTTAATTTTT...,1,Animalia,Arthropoda,Insecta,Hymenoptera,...,2022-03-13,150.0,1.0,5.789432,-73.54972,3,0.333333,1,981359,1.333333
317035,GZYSTR,BOLD:AGZ2097,0,21,AATAAATAATATTAGATTTTGATTACTTCCTCCTTCTTTAATATTA...,3,Animalia,Arthropoda,Insecta,Hymenoptera,...,2022-03-13,150.0,1.0,5.789432,-73.54972,3,1.000000,1,981359,7.000000

In [66]:
all[all['prediction'] != 0].T

sample-eventid,BIOPER00138,G16R5R,G17O2Y,G17RAD,G19AZB,G1AFX8,G1GJFP,G1J9FU,G1KBYO,G1KDXO,...,GZ6AKC,GZ6WBA,GZE9G4,GZF7RH,GZOU3P,GZPO2W,GZSO1T,GZST6D,GZUCZ3,GZYSTR
bin_uri,BOLD:AGE5680,BOLD:AFV0053,BOLD:AFA1866,BOLD:AAE7838,BOLD:ABA8270,BOLD:AGI1221,BOLD:AAB6200,BOLD:ADF9182,BOLD:AAD4432,BOLD:AGO0629,...,BOLD:AFY8279,BOLD:AFU4807,BOLD:ABA8270,BOLD:AGJ1884,BOLD:AFY8925,BOLD:ABA8270,BOLD:AGG9073,BOLD:AAD3923,BOLD:AFA1866,BOLD:AFY8530
occurrences,0,8,0,0,3,0,1,0,3,0,...,84,1,0,6,0,3,0,7,0,16
total_reads,9,254,2,8,195,53,25,5,19,3,...,7918,1534,93,856,2,89,19,58,3,2
tot_repl_w_reads,3,3,1,1,3,2,1,2,1,1,...,3,3,3,3,1,3,1,3,1,1
order,Lepidoptera,Diptera,Diptera,Hymenoptera,Diptera,NaN,Diptera,Diptera,Hymenoptera,Entomobryomorpha,...,Diptera,Diptera,Diptera,Diptera,Diptera,Diptera,Diptera,Hymenoptera,Diptera,Diptera
family,Gelechiidae,Sciaridae,Chironomidae,Formicidae,Sciaridae,NaN,Drosophilidae,Sciaridae,Formicidae,NaN,...,Sciaridae,Ceratopogonidae,Sciaridae,Chironomidae,Stratiomyidae,Sciaridae,Ceratopogonidae,Formicidae,Chironomidae,Psychodidae
genus,NaN,NaN,NaN,Camponotus,Hyperlasion,NaN,Zaprionus,NaN,Camponotus,NaN,...,NaN,NaN,Hyperlasion,NaN,Chiromyza,Hyperlasion,NaN,Pheidole,NaN,NaN
species,NaN,NaN,NaN,Camponotus tendryi,NaN,NaN,Zaprionus indianus,NaN,Camponotus nearcticus,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pheidole spinosa,NaN,NaN
min_reads,2,56,0,0,26,0,0,0,0,0,...,2409,281,23,162,0,24,0,4,0,0
max_reads,4,115,2,8,103,34,25,3,19,3,...,2866,681,41,392,2,35,19,48,3,2
sd_reads,1.0,29.53529,1.154701,4.618802,38.509739,17.039171,14.433757,1.527525,10.969655,1.732051,...,228.522063,206.785718,9.165151,115.902258,1.154701,5.507571,10.969655,24.846194,1.732051,1.154701
lane,NSEQ-00081,NSEQ-00037,NSEQ-00020,NSEQ-00037,NSEQ-00056,NSEQ-00014,NSEQ-00041,NSEQ-00062,NSEQ-00041,NSEQ-00061,...,NSEQ-00020,NSEQ-00060,NSEQ-00062,NSEQ-00037,NSEQ-00041,NSEQ-00056,NSEQ-00060,NSEQ-00061,NSEQ-00020,NSEQ-00020
fieldid,NaN,G16R5R,G17O2Y,G17RAD,G19AZB,G1AFX8,G1GJFP,G1J9FU,G1KBYO,G1KDXO,...,GZ6AKC,GZ6WBA,GZE9G4,GZF7RH,GZOU3P,GZPO2W,GZSO1T,GZST6D,GZUCZ3,GZYSTR
collection_start_date,NaN,2023-04-05,2022-06-23,2023-04-12,2022-10-24,2022-01-12,2022-11-17,2024-01-17,2022-07-08,2024-01-31,...,2022-03-23,2023-07-05,2023-04-05,2023-01-04,2022-10-06,2022-08-01,2023-08-02,2023-10-18,2022-05-25,2022-03-06
collection_end_date,NaN,2023-04-12,2022-06-30,2023-04-19,2022-10-31,2022-01-19,2022-12-01,2024-01-24,2022-07-14,2024-02-08,...,2022-03-30,2023-07-12,2023-04-12,2023-01-11,2022-10-13,2022-08-08,2023-08-09,2023-10-26,2022-06-01,2022-03-13
SumExcessSpecimens,48.0,205.0,138.0,100.0,110.0,257.0,6500.0,41.0,70.0,47.0,...,31.0,168.0,84.0,247.0,5049.0,224.0,265.0,9.0,320.0,150.0
ExcessNumberTaxa,1.0,2.0,3.0,1.0,2.0,3.0,5.0,1.0,3.0,2.0,...,1.0,1.0,2.0,2.0,5.0,1.0,4.0,1.0,4.0,1.0
latitude,NaN,-22.539167,-8.423733,-15.38813,-22.400713,-17.918335,0.335643,-14.43462,38.63542,-22.539656,...,7.052115,-20.062849,-14.435532,-13.409162,0.335331,-22.405592,-17.705435,-22.539656,-8.423698,5.789432
longitude,NaN,45.379967,-74.699905,49.46827,-42.412125,49.20046,6.650312,49.75853,-90.30214,45.379066,...,-75.397995,44.656387,49.766674,48.305386,6.650652,-42.42856,49.457024,45.379066,-74.700005,-73.54972
tot_repl,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
repl_w_reads_fractn,1.0,1.0,0.333333,0.333333,1.0,0.666667,0.333333,0.666667,0.333333,0.333333,...,1.0,1.0,1.0,1.0,0.333333,1.0,0.333333,1.0,0.333333,0.333333
Excess,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
total_reads_per_sample,735301,1273303,1167143,755483,583579,1604347,1153841,803138,498839,153567,...,1327233,643973,1077938,647950,1414273,494880,1505940,89516,1172825,981359
avg_reads,3.0,84.666667,0.666667,2.666667,65.0,17.666667,8.333333,1.666667,6.333333,1.0,...,2639.333333,511.333333,31.0,285.333333,0.666667,29.666667,6.333333,19.333333,1.0,0.666667
prediction,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
targets,0.0,0.024768,0.0,0.0,0.002879,0.0,0.000338,0.0,0.008065,0.0,...,0.077277,0.020408,0.0,0.02214,0.0,0.012397,0.0,0.065421,0.0,0.012432
sample_labels,BIOPER00138,G16R5R,G17O2Y,G17RAD,G19AZB,G1AFX8,G1GJFP,G1J9FU,G1KBYO,G1KDXO,...,GZ6AKC,GZ6WBA,GZE9G4,GZF7RH,GZOU3P,GZPO2W,GZSO1T,GZST6D,GZUCZ3,GZYSTR
bin_labels,BOLD:AGE5680,BOLD:AFV0053,BOLD:AFA1866,BOLD:AAE7838,BOLD:ABA8270,BOLD:AGI1221,BOLD:AAB6200,BOLD:ADF9182,BOLD:AAD4432,BOLD:AGO0629,...,BOLD:AFY8279,BOLD:AFU4807,BOLD:ABA8270,BOLD:AGJ1884,BOLD:AFY8925,BOLD:ABA8270,BOLD:AGG9073,BOLD:AAD3923,BOLD:AFA1866,BOLD:AFY8530
latent_0,-0.000258,-0.000057,0.001245,0.000011,-0.001057,-0.00096,-0.000017,-0.000503,-0.000316,0.012768,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latent_1,0.000042,-0.000078,-0.000515,-0.000224,0.000369,0.000303,-0.000004,0.00025,0.000339,-0.013656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latent_2,-0.000017,-0.000079,-0.000278,-0.000078,0.000086,0.000106,-0.000162,0.000147,-0.000073,-0.007586,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latent_3,0.000013,-0.000094,-0.000126,-0.000077,0.000008,0.000032,-0.000119,0.000052,-0.000039,-0.0027,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latent_4,-0.000036,0.000062,0.000551,0.000089,-0.000274,-0.000279,0.000177,-0.000209,0.000176,0.010816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latent_5,0.000002,-0.000097,-0.000149,-0.000075,0.000049,0.000057,-0.000138,0.000055,0.000012,-0.00395,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latent_6,0.000012,0.000084,0.000564,0.000046,-0.000256,-0.000347,0.000223,-0.000245,0.000219,0.012844,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latent_7,-0.000134,0.00001,0.000975,0.000054,-0.000675,-0.000704,0.000091,-0.000433,-0.000063,0.014298,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latent_8,-0.000048,0.000047,0.000475,0.000081,-0.000191,-0.000208,0.00016,-0.000065,0.000229,0.009644,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latent_9,0.00046,0.000209,-0.001573,0.000088,0.001586,0.001378,0.00018,0.000821,0.000705,-0.006649,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN